# Generated by Django 5.0.6 on 2024-06-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_layout_patch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackarea',
            name='custom_field_data',
        ),
    ]
