# Generated by Django 5.0.6 on 2024-06-28 20:10

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_layout_patch', '0002_remove_rackarea_custom_field_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='rackarea',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
